### ISSUE TITLE
Creating a Personal Food item creates issue with Net Carbs

### ISSUE THREAD

**Issue by thepennster** [Surye/mfp-keto-userscript#36] opened 2017-07-05 16:42 UTC
I added a personal food in MFP with all the nutrition facts, but when I add it to my diary, the script seems to add the amount of Daily Fiber into my Net Carbs daily goal amount. My Net Carb daily goal is 16, but when I add my food item, the goals shoots up to 31, and the only math that adds up is that it's taking the Dietary Fiber in my food and adding it to the daily goal in Net Carbs. Thank you for looking into this!

PS - I should mention that I have messed around with different combinations on my personal food to the same results, i.e. there are really 19g of carbs and 15g of fiber (for 4g of Net Carbs), but same results.

![mfp script](https://user-images.githubusercontent.com/16439177/27874880-15f00cb0-6166-11e7-8c2c-d2929f7279bb.jpg)

**Comment by dayreiner** [comment] 2017-07-26 03:29
Noticed this happening on mine as well using chrome with foods in the database that people have labelled "net carbs". The problem is folks put the net carbs down and then also include the fiber grams, which messes up the calculations since fiber is being subtracted from the carb total. 

@thepennster Your entry for example shows 4g carbs, but 15g fiber. This messes up the math as subtracting 15g fiber for 4g carbs would be a negative number.

Confirmed this with a quick test using a "net carbs" quest bar entry I found in the DB with more fiber than carbs:

<img width="743" alt="screen shot 2017-07-25 at 11 21 13 pm" src="https://user-images.githubusercontent.com/5184541/28603095-170a46d0-7190-11e7-8b1c-e5816573ff15.png">

Note the messed up values in the totals. I then went ahead and made my own "net carbs" version of the same item, but instead I left the carbs at 4g to reflect the net carbs and set the fiber to 0. This time there are no issues with the calculations:

<img width="738" alt="screen shot 2017-07-25 at 11 20 33 pm" src="https://user-images.githubusercontent.com/5184541/28603127-4694e554-7190-11e7-8e88-f6b4424bc7fc.png">

For now, I'm avoiding DB entries that list net carbs but fail to remove the fiber to ensure the totals don't go all screwy.

**Comment by thepennster** [comment] 2017-07-27 14:48
@dayreiner thank you for replying. I have gone ahead and edited the food to remove the Fiber as you suggested, and indeed it fixed the problem. I still think there's something off with the script, because I went back and tested it by putting in the real number of carbs and fiber (22 Carbs and 19 Fiber = 3 Net Carbs) and the problem persists and throws off the Daily Goal number for Net Carbs (in my case it should be 16, but it is now 35)....

![2017-07-27_7-41-33](https://user-images.githubusercontent.com/16439177/28676503-a1ac2974-729f-11e7-862b-70eeab84a44a.png)

**Comment by david86au** [comment] 2017-08-09 10:40
Hi,

I just wanted to add I am having the exact same issues, it is very annoying.

Are there any plans for a fix?

Cheers

**Comment by Surye** [comment] 2017-08-25 15:27
This is all the reasons I didnt want "net carbs" support, it complicates things and things get entered differently.

But I think I have this particular issue fixed now.

**Closed as completed by Surye** 2017-08-25 15:27 UTC
