### ISSUE TITLE
Problem calculating Net Carbs

### ISSUE THREAD

**Issue by cmoons** [Surye/mfp-keto-userscript#33] opened 2017-05-21 21:58 UTC
Just noticing today the plug-in is not calculating the Net Carbs properly. I have entered food with 9g Total Carbs and 4g Dietary fiber. The "Net Carbs" column is showing up, but it is displaying 9g for the value, when usually it would show 5g in this case.

**Comment by Surye** [comment] 2017-05-25 15:06
Does the food entry list "Net Carbs" in it's title?

**Comment by mulligan711** [comment] 2017-05-26 10:08
It's working again!  Thank you so much for being attentive and resolving.  Cheers!

**Comment by cmoons** [comment] 2017-05-26 23:29
Yes - Here is the entry

Breyers - Carb Smart Vanilla Ice Cream (True Net Carbs), 0.5 cup (66g)
<http://www.myfitnesspal.com/food/diary/cmoonier#>

**Comment by Surye** [comment] 2017-06-14 18:29
That is by design, net carbs is already net carbs.

**Closed as completed by Surye** 2017-06-14 18:29 UTC
