### ISSUE TITLE
Mac MFP layout issue 

### ISSUE THREAD

**Issue by nybe** [Surye/mfp-keto-userscript#20] opened 2016-07-12 19:46 UTC
having major problems with layout issues on both chrome and safari in Mac. 

See attached image:

[messed up MFP net carb layout.](http://i.imgur.com/kEkM0Wx.png)

**Comment by ghost** [comment] 2016-07-13 03:30
I'm seeing the same issue in Firefox.  It started, a couple of days ago.  Was working fine, before

**Comment by ryanhallfayce** [comment] 2016-07-13 12:27
Seeing this in chrome on Mac as well.

**Comment by revaewytak** [comment] 2016-07-13 12:30
Seeing this in Chrome on Windows 10 also

**Comment by Surye** [comment] 2016-07-13 20:54
Dupe of #19

**Closed as completed by Surye** 2016-07-13 20:54 UTC

**Comment by nybe** [comment] 2016-07-13 21:58
thanks! much appreciated

**Comment by ghost** [comment] 2016-07-14 04:26
Thank you!  It’s working for me, now.
