### ISSUE TITLE
Net Carbs not adding correctly

### ISSUE THREAD

**Issue by ghost** [Surye/mfp-keto-userscript#50] opened 2019-01-17 09:43 UTC
A few others have noticed that sometimes the Net Carbs total is incorrect. In the total row, it is calculating the Total Net Carbs as TNC = Total Carbs - Total Fibre:

![image](https://user-images.githubusercontent.com/46778681/51309174-8d9c7f80-1a8f-11e9-8858-19cb7c604648.png)

But, as you can see from the image, this results in a negative value, which is obviously wrong.

I think a better calculation would be to simply sum the meal totals for Net Carbs:

![image](https://user-images.githubusercontent.com/46778681/51309346-e3712780-1a8f-11e9-86c8-df11a33507c9.png)

This would also tally with the remaining value (5 in my image).

Daily Goal = 19
Net Carbs = 12 + 2 = 14
Remaining = 5

Can the script be updated to calculate the Total Net Carbs this way?

**Comment by vcastellano-spl** [comment] 2019-01-24 18:32
This is not a bug, it's because you have food with bad data. You can't have more fiber than carbs.

**Comment by Surye** [comment] 2019-01-24 18:42
This is not a bug, it's because you have food with bad data. You can't have more fiber than carbs. I am also aware that food in UK and other countries have fiber already removed, so this script isn't necessary. But if you mix them they are not going to work. Total Net Carbs as TNC = Total Carbs - Total Fibre is by definition.

**Comment by Surye** [comment] 2019-01-24 19:44
I stand corrected, there indeed was a calculation bug (those pesky "net carb" entries in MFP, I hate them!). Pushed a fix.

**Closed as completed by Surye** 2019-01-24 19:44 UTC

**Comment by ghost** [comment] 2019-02-05 03:45
Here is my modified version that fixes the Net Carbs calculation issue. It also keeps the Daily Goal and Remaining totals intact.
[MyFitnessPal Percentages and Net Carbs.user.js.txt](https://github.com/Surye/mfp-keto-userscript/files/2830663/MyFitnessPal.Percentages.and.Net.Carbs.user.js.txt)
