### ISSUE TITLE
Net carbs amounts are off.

### ISSUE THREAD

**Issue by mlynnm727** [Surye/mfp-keto-userscript#32] opened 2017-05-16 19:52 UTC
Hi I'm noticing today that the net carb amounts are adding in additional amounts for items that have not been entered. 

![image](https://cloud.githubusercontent.com/assets/3142938/26125201/eb01b7ba-3a46-11e7-8b86-65c65335643c.png)
![image](https://cloud.githubusercontent.com/assets/3142938/26125274/2ec7b094-3a47-11e7-9f92-cfd9870c1bc2.png)

Thanks.

**Comment by Surye** [comment] 2017-05-16 19:57
I can't seem to reproduce.. Do you have a public diary link?

**Comment by mlynnm727** [comment] 2017-05-16 20:38
http://www.myfitnesspal.com/food/diary/mlynnm727

Thanks

**Comment by mulligan711** [comment] 2017-05-18 19:32
I am having the same issue and carbs don't always subtract fiber.

![image](https://cloud.githubusercontent.com/assets/28732781/26220089/40a83b3c-3bdf-11e7-9271-49680061a990.png)


http://www.myfitnesspal.com/profile/thetammymcdaniel

**Comment by mulligan711** [comment] 2017-05-20 15:33
This *was* a cool utility.  :-\  I wish MFP would just allow Net Carb calculations even if you had to upgrade to use it.

**Comment by Surye** [comment] 2017-05-20 16:02
The original issue is just a display bug I need to track down, the totals
are still correct.

**Comment by Surye** [comment] 2017-05-20 16:03
@mulligan711 your diary is private even to friends so I can't see what
you're seeing. Is it not subtracting on foods marked as net carbs?

**Comment by mulligan711** [comment] 2017-05-21 01:54
I didn't realize it was private to friends too.  I just changed it.

Tammy

On May 20, 2017, at 12:03, Vincent Castellano <notifications@github.com<mailto:notifications@github.com>> wrote:

@mulligan711 your diary is private even to friends so I can't see what
you're seeing. Is it not subtracting on foods marked as net carbs?

-

**Comment by LohikaarmeVaeltaja** [comment] 2017-05-25 08:36
Here's my diary: http://www.myfitnesspal.com/food/diary/lohikaarme_vaeltaja

**Comment by mulligan711** [comment] 2017-05-25 10:27
It didn't work consistently so I deleted it.  I am just going to use a spreadsheet or figure net carbs out in my head.  I will miss the footer pie charts.


On May 25, 2017, at 04:36, LohikaarmeVaeltaja <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's my diary: http://www.myfitnesspal.com/food/diary/lohikaarme_vaeltaja

-

**Comment by Surye** [comment] 2017-05-25 14:42
The problem is in #31. It is adding the "already counted" fiber for the whole day to every meal. I have a fix coming here, either reverting the net carb awareness or making it update per meal properly.

**Comment by Surye** [comment] 2017-05-25 15:06
OK, this problem should be fixed in 1.13

**Comment by aikar** [comment] 2017-05-26 01:33
Cool, I was about to go figure the problem out. I did notice the issue too just hadn't gotten around to figuring it out yet.

**Comment by mulligan711** [comment] 2017-05-26 10:09
It's working again! Thank you so much for being attentive and resolving. Cheers!

**Closed as completed** 2017-05-26 14:44 UTC
